/* eslint-disable */
// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

const awsmobile = {
    "aws_project_region": "us-east-1",
    "aws_appsync_graphqlEndpoint": "https://u2czlimewbcx3eb3xehihaxm64.appsync-api.us-east-1.amazonaws.com/graphql",
    "aws_appsync_region": "us-east-1",
    "aws_appsync_authenticationType": "API_KEY",
    "aws_appsync_apiKey": "da2-zke77z5fg5aujm4n3jawwfukva",
    "aws_cognito_identity_pool_id": "us-east-1:daac3e37-e458-4ab9-a41b-5b43722d28b4",
    "aws_cognito_region": "us-east-1",
    "aws_user_pools_id": "us-east-1_snSIV3OXb",
    "aws_user_pools_web_client_id": "60r1nqdks4lnutpj1ujj3eksrq",
    "oauth": {},
    "aws_cognito_username_attributes": [],
    "aws_cognito_social_providers": [],
    "aws_cognito_signup_attributes": [
        "EMAIL"
    ],
    "aws_cognito_mfa_configuration": "OFF",
    "aws_cognito_mfa_types": [
        "SMS"
    ],
    "aws_cognito_password_protection_settings": {
        "passwordPolicyMinLength": 8,
        "passwordPolicyCharacters": []
    },
    "aws_cognito_verification_mechanisms": [
        "EMAIL"
    ],
    "aws_user_files_s3_bucket": "amplifyreactgraphql903d7948dc3a4243a5d41240adb1111059-staging",
    "aws_user_files_s3_bucket_region": "us-east-1"
};


export default awsmobile;
